server:
  port: 9992

spring:
  application:
    name: API-USERS
  cloud:
    nacos:
      server-addr: 192.168.10.11:8848
  redis:
    host: 192.168.10.11
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:3306/video?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fun.verda.entity