server:
  port: 9993

spring:
  application:
    name: API-VIDEOS
  cloud:
    nacos:
      server-addr: 192.168.10.11:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:3306/video?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.10.11
    port: 6379
  rabbitmq:
    host: 192.168.10.11
    port: 5672
    username: guest
    password: guest
    virtual-host: / #类似于数据库概念


mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: fun.verda.entity
