server:
  port: 8981
spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      server-addr: 192.168.10.11:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:3306/video?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  redis:
    host: 192.168.10.11
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fun.verda.entity


logging:
  level:
    fun.verda.dao: debug