server:
  port: 9991

spring:
  application:
    name: API-CATEGORIES
  cloud:
    nacos:
      server-addr: 192.168.10.11:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:3306/video?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fun.verda.entity


